// This file was auto-generated by SceneListCheck!

public enum Scenes 
{
	StartAnimation = 0,
	MainMenu = 1,
	lev_1 = 2,
	lev_2 = 3,
	lev_3 = 4,
	lev_4 = 5,
	lev_5 = 6,
	lev_6 = 7,
	lev_7 = 8,
	lev_8 = 9,
	lev_1b = 10,
	lev_3b = 11,
	lev_2b = 12,
	lev_4b = 13,
	lev_9 = 14,
	lev_10 = 15,
	lev_11 = 16,
	lev_12 = 17,
	lev_13 = 18,
	lev_14 = 19,
	lev_15 = 20,
	lev_16 = 21,
	lev_17 = 22,
	lev_18 = 23,
	lev_19 = 24,
	lev_20 = 25,
	lev_21 = 26,
	lev_22 = 27,
	lev_23 = 28
}

